### ISSUE TITLE
trait FromSql is not implemented for rust_decimal::Decimal with postgres 0.19

### ISSUE THREAD

**Issue by guoguojin** [paupino/rust-decimal#293]
When using the 0.19 version of the postgres library, I get the error above. When I changed to version 0.18 it works without any issues.

**Comment by paupino** [comment]
I _think_ this is solved in the upcoming release, even though it targets `0.18`, which I'll be releasing shortly.

Going forward, I may need to rethink these soft dependencies, perhaps looking at aliasing them in the Cargo file using the `package` key.

**Comment by guoguojin** [comment]
Hi, I just updated to the 1.9 crate for rust-decimal and I'm still getting the not implemented error when using postgres 0.19. The same code compiles without any problems when I use the postgres 0.18 version, so unless I'm doing something wrong, I don't think this has been resolved.

Let me know if you need any additional information.

Thanks.

**Comment by paupino** [comment]
Hi @guoguojin - I think this should be resolved if you use the `master` branch instead. A merge upgrading the dependencies was done on Dec 31 that should resolve things however that has yet to be released.
Another option is to maybe look at using the [`[patch`]](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) directive in `Cargo.toml` which _may_ help overriding this in the meantime. The files requiring patch are here: https://github.com/paupino/rust-decimal/pull/302/files

**Comment by guoguojin** [comment]
Okay, thanks for the update. It's just a personal project to learn more about rust so I'm fine using the 0.18 postgres libraries until the fix has been released.
